// Code generated by mockery v1.0.0. DO NOT EDIT.

package executor

import context "context"

import mock "github.com/stretchr/testify/mock"
import sql "database/sql"
import sqlx "github.com/jmoiron/sqlx"

// ExecutorMock is an autogenerated mock type for the Executor type
type ExecutorMock struct {
	mock.Mock
}

// ExecContext provides a mock function with given fields: ctx, execerContext, query, args
func (_m *ExecutorMock) ExecContext(ctx context.Context, execerContext sqlx.ExecerContext, query string, args []interface{}) (sql.Result, error) {
	ret := _m.Called(ctx, execerContext, query, args)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(context.Context, sqlx.ExecerContext, string, []interface{}) sql.Result); ok {
		r0 = rf(ctx, execerContext, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, sqlx.ExecerContext, string, []interface{}) error); ok {
		r1 = rf(ctx, execerContext, query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContext provides a mock function with given fields: ctx, queryerContext, dest, query, args
func (_m *ExecutorMock) GetContext(ctx context.Context, queryerContext sqlx.QueryerContext, dest interface{}, query string, args []interface{}) error {
	ret := _m.Called(ctx, queryerContext, dest, query, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlx.QueryerContext, interface{}, string, []interface{}) error); ok {
		r0 = rf(ctx, queryerContext, dest, query, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MustExecContext provides a mock function with given fields: ctx, execerContext, query, args
func (_m *ExecutorMock) MustExecContext(ctx context.Context, execerContext sqlx.ExecerContext, query string, args []interface{}) sql.Result {
	ret := _m.Called(ctx, execerContext, query, args)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(context.Context, sqlx.ExecerContext, string, []interface{}) sql.Result); ok {
		r0 = rf(ctx, execerContext, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	return r0
}

// PreparexContext provides a mock function with given fields: ctx, preparerContext, query
func (_m *ExecutorMock) PreparexContext(ctx context.Context, preparerContext sqlx.PreparerContext, query string) (*sqlx.Stmt, error) {
	ret := _m.Called(ctx, preparerContext, query)

	var r0 *sqlx.Stmt
	if rf, ok := ret.Get(0).(func(context.Context, sqlx.PreparerContext, string) *sqlx.Stmt); ok {
		r0 = rf(ctx, preparerContext, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Stmt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, sqlx.PreparerContext, string) error); ok {
		r1 = rf(ctx, preparerContext, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectContext provides a mock function with given fields: ctx, queryerContext, dest, query, args
func (_m *ExecutorMock) SelectContext(ctx context.Context, queryerContext sqlx.QueryerContext, dest interface{}, query string, args []interface{}) error {
	ret := _m.Called(ctx, queryerContext, dest, query, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlx.QueryerContext, interface{}, string, []interface{}) error); ok {
		r0 = rf(ctx, queryerContext, dest, query, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
