load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "errors",
    srcs = ["errors.go"],
    importpath = "compass.com/postgres/temporarytables/errors",
    visibility = ["//visibility:public"],
    deps = ["@com_github_pkg_errors//:errors"],
)
