// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: people/v1/service.proto

package peoplev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_people_v1_service_proto protoreflect.FileDescriptor

const file_people_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17people/v1/service.proto\x12\tpeople.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x16people/v1/models.proto2\x7f\n" +
	"\rPeopleService\x12n\n" +
	"\x05Login\x12\x17.people.v1.LoginRequest\x1a\x18.people.v1.LoginResponse\"2\x92A\x10\n" +
	"\x06people\x12\x06登录\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/people:loginB~\x92AG\x12E\n" +
	"\x0fWebx People API\x12.用户与认证相关的 gRPC + REST 接口。2\x02v1Z2github.com/dafsic/webx/proto_go/people/v1;peoplev1b\x06proto3"

var file_people_v1_service_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: people.v1.LoginRequest
	(*LoginResponse)(nil), // 1: people.v1.LoginResponse
}
var file_people_v1_service_proto_depIdxs = []int32{
	0, // 0: people.v1.PeopleService.Login:input_type -> people.v1.LoginRequest
	1, // 1: people.v1.PeopleService.Login:output_type -> people.v1.LoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_people_v1_service_proto_init() }
func file_people_v1_service_proto_init() {
	if File_people_v1_service_proto != nil {
		return
	}
	file_people_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_people_v1_service_proto_rawDesc), len(file_people_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_people_v1_service_proto_goTypes,
		DependencyIndexes: file_people_v1_service_proto_depIdxs,
	}.Build()
	File_people_v1_service_proto = out.File
	file_people_v1_service_proto_goTypes = nil
	file_people_v1_service_proto_depIdxs = nil
}
