load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "pgdumpschema",
    srcs = ["pgdumpschema.go"],
    importpath = "compass.com/postgres/pgdumpschema",
    visibility = ["//visibility:public"],
)
