// Package pgdumpschema calls pg_dump and dumps a (slightly cleaned)
// database schema file.
package pgdumpschema

import (
	"bytes"
	"errors"
	"io"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

const headerComment = "-- Generated by pgdumpschema using pg_dump -s\n\n"

// Config controls how pg_dump is run and where the output goes.
type Config struct {
	Database string    // Database name (required)
	Host     string    // Host name or IP address (defaults to PGHOST)
	NoClean  bool      // Don't clean comments and blank lines from output
	NoHeader bool      // Don't write the "generated by" header comment
	Password string    // Authentication password (defaults to PGPASSWORD)
	PGDump   string    // pg_dump executable name (defaults to "pg_dump")
	Port     int       // Database port (defaults to PGPORT or 5432)
	Schemas  []string  // Schemas to dump (default is to dump all schemas)
	Username string    // Authentication username (defaults to PGUSER or current user)
	Writer   io.Writer // Writer to write schema dump to (defaults to stdout)
}

// Dump dumps a database schema based on the given config.
func Dump(config *Config) error {
	if config == nil {
		return errors.New("must supply a non-nil config")
	}
	if config.Database == "" {
		return errors.New("must supply a database name")
	}

	program := config.PGDump
	if program == "" {
		program = "pg_dump"
	}
	args := []string{"-s", "-d", config.Database, "-w"}

	// If the pg dump command begins with docker, we are most likely attempting to run
	// docker exec <container name> pg_dump ...
	// In this case, we need to set program to docker, and prepend exec, container_name, and pg_dump to args
	if strings.HasPrefix(config.PGDump, "docker") {
		program = "docker"
		args = append(strings.Split(config.PGDump, " ")[1:], args...)
	}

	for _, schema := range config.Schemas {
		args = append(args, "-n", schema)
	}
	if config.Host != "" {
		args = append(args, "-h", config.Host)
	}
	if config.Port != 0 {
		args = append(args, "-p", strconv.Itoa(config.Port))
	}
	if config.Username != "" {
		args = append(args, "-U", config.Username)
	}

	cmd := exec.Command(program, args...)
	if config.Password != "" {
		cmd.Env = append(os.Environ(), "PGPASSWORD="+config.Password)
	}
	buf := &bytes.Buffer{}
	cmd.Stdout = buf

	err := cmd.Run()
	if err != nil {
		return err
	}
	output := buf.Bytes()
	if !config.NoClean {
		output = clean(output)
	}
	writer := config.Writer
	if writer == nil {
		writer = os.Stdout
	}
	if !config.NoHeader {
		_, err = io.WriteString(writer, headerComment)
		if err != nil {
			return err
		}
	}
	_, err = writer.Write(output)
	return err
}

var (
	newlineBytes = []byte("\n")
	commentBytes = []byte("--")
)

// Clean up pg_dump's schema output (removing comments and multiple
// blank lines).
func clean(input []byte) []byte {
	prevBlank := true
	output := make([]byte, 0, len(input))
	lines := bytes.Split(input, newlineBytes)
	for _, line := range lines {
		if bytes.HasPrefix(line, commentBytes) {
			// Ignore SQL comment lines (pg_dump )
			continue
		}
		curBlank := len(bytes.TrimSpace(line)) == 0
		if prevBlank && curBlank {
			// Ignore multiple blank lines in a row
			continue
		}
		prevBlank = curBlank
		output = append(output, line...)
		output = append(output, '\n')
	}
	return output
}
