// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: catalog/v1/service.proto

package catalogv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_catalog_v1_service_proto protoreflect.FileDescriptor

const file_catalog_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/service.proto\x12\n" +
	"catalog.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17catalog/v1/models.proto2\xc8\x05\n" +
	"\x0eCatalogService\x12\x87\x01\n" +
	"\tListItems\x12\x1c.catalog.v1.ListItemsRequest\x1a\x1d.catalog.v1.ListItemsResponse\"=\x92A\x1d\n" +
	"\acatalog\x12\x12获取菜单列表\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/catalog/items\x12\x86\x01\n" +
	"\aGetItem\x12\x1a.catalog.v1.GetItemRequest\x1a\x1b.catalog.v1.GetItemResponse\"B\x92A\x1d\n" +
	"\acatalog\x12\x12获取单个菜品\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/catalog/items/{id}\x12\x87\x01\n" +
	"\n" +
	"CreateItem\x12\x1d.catalog.v1.CreateItemRequest\x1a\x1e.catalog.v1.CreateItemResponse\":\x92A\x17\n" +
	"\acatalog\x12\f新增菜品\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/catalog/items\x12\x8c\x01\n" +
	"\n" +
	"UpdateItem\x12\x1d.catalog.v1.UpdateItemRequest\x1a\x1e.catalog.v1.UpdateItemResponse\"?\x92A\x17\n" +
	"\acatalog\x12\f修改菜品\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/api/v1/catalog/items/{id}\x12\x89\x01\n" +
	"\n" +
	"DeleteItem\x12\x1d.catalog.v1.DeleteItemRequest\x1a\x1e.catalog.v1.DeleteItemResponse\"<\x92A\x17\n" +
	"\acatalog\x12\f删除菜品\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/catalog/items/{id}B\x90\x01\x92AW\x12U\n" +
	"\x10Webx Catalog API\x12=酒吧菜单（菜品 + 价格）管理 gRPC + REST 接口。2\x02v1Z4github.com/dafsic/webx/proto_go/catalog/v1;catalogv1b\x06proto3"

var file_catalog_v1_service_proto_goTypes = []any{
	(*ListItemsRequest)(nil),   // 0: catalog.v1.ListItemsRequest
	(*GetItemRequest)(nil),     // 1: catalog.v1.GetItemRequest
	(*CreateItemRequest)(nil),  // 2: catalog.v1.CreateItemRequest
	(*UpdateItemRequest)(nil),  // 3: catalog.v1.UpdateItemRequest
	(*DeleteItemRequest)(nil),  // 4: catalog.v1.DeleteItemRequest
	(*ListItemsResponse)(nil),  // 5: catalog.v1.ListItemsResponse
	(*GetItemResponse)(nil),    // 6: catalog.v1.GetItemResponse
	(*CreateItemResponse)(nil), // 7: catalog.v1.CreateItemResponse
	(*UpdateItemResponse)(nil), // 8: catalog.v1.UpdateItemResponse
	(*DeleteItemResponse)(nil), // 9: catalog.v1.DeleteItemResponse
}
var file_catalog_v1_service_proto_depIdxs = []int32{
	0, // 0: catalog.v1.CatalogService.ListItems:input_type -> catalog.v1.ListItemsRequest
	1, // 1: catalog.v1.CatalogService.GetItem:input_type -> catalog.v1.GetItemRequest
	2, // 2: catalog.v1.CatalogService.CreateItem:input_type -> catalog.v1.CreateItemRequest
	3, // 3: catalog.v1.CatalogService.UpdateItem:input_type -> catalog.v1.UpdateItemRequest
	4, // 4: catalog.v1.CatalogService.DeleteItem:input_type -> catalog.v1.DeleteItemRequest
	5, // 5: catalog.v1.CatalogService.ListItems:output_type -> catalog.v1.ListItemsResponse
	6, // 6: catalog.v1.CatalogService.GetItem:output_type -> catalog.v1.GetItemResponse
	7, // 7: catalog.v1.CatalogService.CreateItem:output_type -> catalog.v1.CreateItemResponse
	8, // 8: catalog.v1.CatalogService.UpdateItem:output_type -> catalog.v1.UpdateItemResponse
	9, // 9: catalog.v1.CatalogService.DeleteItem:output_type -> catalog.v1.DeleteItemResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_v1_service_proto_init() }
func file_catalog_v1_service_proto_init() {
	if File_catalog_v1_service_proto != nil {
		return
	}
	file_catalog_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_service_proto_rawDesc), len(file_catalog_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_service_proto_goTypes,
		DependencyIndexes: file_catalog_v1_service_proto_depIdxs,
	}.Build()
	File_catalog_v1_service_proto = out.File
	file_catalog_v1_service_proto_goTypes = nil
	file_catalog_v1_service_proto_depIdxs = nil
}
