// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: orders/v1/service.proto

package ordersv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_orders_v1_service_proto protoreflect.FileDescriptor

const file_orders_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17orders/v1/service.proto\x12\torders.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x16orders/v1/models.proto2\xa8\x04\n" +
	"\fOrderService\x12z\n" +
	"\vCreateOrder\x12\x1d.orders.v1.CreateOrderRequest\x1a\x1e.orders.v1.CreateOrderResponse\",\x92A\x10\n" +
	"\x06orders\x12\x06下单\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/orders\x12y\n" +
	"\bGetOrder\x12\x1a.orders.v1.GetOrderRequest\x1a\x1b.orders.v1.GetOrderResponse\"4\x92A\x16\n" +
	"\x06orders\x12\f查询订单\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/orders/{id}\x12z\n" +
	"\n" +
	"ListOrders\x12\x1c.orders.v1.ListOrdersRequest\x1a\x1d.orders.v1.ListOrdersResponse\"/\x92A\x16\n" +
	"\x06orders\x12\f订单列表\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/orders\x12\xa4\x01\n" +
	"\x11UpdateOrderStatus\x12#.orders.v1.UpdateOrderStatusRequest\x1a$.orders.v1.UpdateOrderStatusResponse\"D\x92A\x1c\n" +
	"\x06orders\x12\x12更新订单状态\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/api/v1/orders/{id}/statusB\x8c\x01\x92AU\x12S\n" +
	"\x0fWebx Orders API\x12<酒吧点单（下单 + 出品状态）gRPC + REST 接口。2\x02v1Z2github.com/dafsic/webx/proto_go/orders/v1;ordersv1b\x06proto3"

var file_orders_v1_service_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),        // 0: orders.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),           // 1: orders.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),         // 2: orders.v1.ListOrdersRequest
	(*UpdateOrderStatusRequest)(nil),  // 3: orders.v1.UpdateOrderStatusRequest
	(*CreateOrderResponse)(nil),       // 4: orders.v1.CreateOrderResponse
	(*GetOrderResponse)(nil),          // 5: orders.v1.GetOrderResponse
	(*ListOrdersResponse)(nil),        // 6: orders.v1.ListOrdersResponse
	(*UpdateOrderStatusResponse)(nil), // 7: orders.v1.UpdateOrderStatusResponse
}
var file_orders_v1_service_proto_depIdxs = []int32{
	0, // 0: orders.v1.OrderService.CreateOrder:input_type -> orders.v1.CreateOrderRequest
	1, // 1: orders.v1.OrderService.GetOrder:input_type -> orders.v1.GetOrderRequest
	2, // 2: orders.v1.OrderService.ListOrders:input_type -> orders.v1.ListOrdersRequest
	3, // 3: orders.v1.OrderService.UpdateOrderStatus:input_type -> orders.v1.UpdateOrderStatusRequest
	4, // 4: orders.v1.OrderService.CreateOrder:output_type -> orders.v1.CreateOrderResponse
	5, // 5: orders.v1.OrderService.GetOrder:output_type -> orders.v1.GetOrderResponse
	6, // 6: orders.v1.OrderService.ListOrders:output_type -> orders.v1.ListOrdersResponse
	7, // 7: orders.v1.OrderService.UpdateOrderStatus:output_type -> orders.v1.UpdateOrderStatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_v1_service_proto_init() }
func file_orders_v1_service_proto_init() {
	if File_orders_v1_service_proto != nil {
		return
	}
	file_orders_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_v1_service_proto_rawDesc), len(file_orders_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_v1_service_proto_goTypes,
		DependencyIndexes: file_orders_v1_service_proto_depIdxs,
	}.Build()
	File_orders_v1_service_proto = out.File
	file_orders_v1_service_proto_goTypes = nil
	file_orders_v1_service_proto_depIdxs = nil
}
