// Code generated by mockery v1.0.0. DO NOT EDIT.

package postgres

import context "context"
import mock "github.com/stretchr/testify/mock"
import sqlx "github.com/jmoiron/sqlx"

// DatabaseMock is an autogenerated mock type for the Database type
type DatabaseMock struct {
	mock.Mock
}

// Config provides a mock function with given fields:
func (_m *DatabaseMock) Config() *DbConf {
	ret := _m.Called()

	var r0 *DbConf
	if rf, ok := ret.Get(0).(func() *DbConf); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DbConf)
		}
	}

	return r0
}

// IsEnabled provides a mock function with given fields:
func (_m *DatabaseMock) IsEnabled() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Session provides a mock function with given fields:
func (_m *DatabaseMock) Session() *sqlx.DB {
	ret := _m.Called()

	var r0 *sqlx.DB
	if rf, ok := ret.Get(0).(func() *sqlx.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.DB)
		}
	}

	return r0
}

// Transact provides a mock function with given fields: ctx, txFunc
func (_m *DatabaseMock) Transact(ctx context.Context, txFunc func(*sqlx.Tx) error) error {
	ret := _m.Called(ctx, txFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*sqlx.Tx) error) error); ok {
		r0 = rf(ctx, txFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactReadOnly provides a mock function with given fields: ctx, txFunc
func (_m *DatabaseMock) TransactReadOnly(ctx context.Context, txFunc func(*sqlx.Tx) error) error {
	ret := _m.Called(ctx, txFunc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*sqlx.Tx) error) error); ok {
		r0 = rf(ctx, txFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
